### ISSUE TITLE
Refactor parse_op for Operations and ModuleOp

### ISSUE THREAD

**Issue by georgebisbas** [xdslproject/xdsl#233]
```
`def rewrite_and_compare` may be also called with an Operation as arg:
as in:
    def rewrite_module(self, op: (ModuleOp | Operation)):
because parse_op return an Operation
```
Check:
https://github.com/xdslproject/xdsl/blob/main/tests/pattern_rewriter_test.py#L26

**Comment by webmiche** [comment]
IMO, the parser should get a function `parse_module` that checks that the given operation is indeed a module. Or we could use `rewrite_op` here instead of `rewrite_module`, though I think that this does not really solve the problem as the crucial insight here is that MLIR (and our xdsl-opt) expects a module as the top-level operation.
