### ISSUE TITLE
Assembly format does not print/parse dialect attributes correctly

### ISSUE THREAD

**Issue by alexarice** [xdslproject/xdsl#2807]
I believe that dialect attributes are not being parsed correctly by the assembly format. Take the following minimal example, which I have arbitrarily defined as part of the qssa dialect:
```
@irdl_op_definition
class MyTest(IRDLOperation):
    name = "qssa.mytest"

    test = prop_def(LLVMArrayType)

    assembly_format = "$test attr-dict"
```
The following can be parsed:
```
"qssa.mytest"()<{test = !llvm.array<2xi32>}>: () -> ()
```
but it is printed as follows:
```
qssa.mytest <2 x i32>
```
My understanding is that it should be printed as:
```
qssa.mytest !llvm.array<2 x i32>
```
I believe this is a bug in the assembly format parser, though this could just be a problem with my understanding/ the way I'm using the assembly format.

**Comment by superlopuh** [comment]
@PapyChacal, is this expected?

**Comment by PapyChacal** [comment]
It is expected in our implementation; I'm genuinely not sure if this is expected in MLIR's implementation on the top of my head.

The former example:
```
"qssa.mytest"()<{test = !llvm.array<2xi32>}>: () -> ()
```
Is in generic syntax, so expects fully qualified attributes as above.

The latter:
```
qssa.mytest <2 x i32>
```
Is in *custom* syntax inferred by the declarative syntax framework.
The logic is, because you constraint the attribute in a way that we can *infer* it is an `!llvm.array`, it just elides the name in custom syntax.

So:
- As long as it roundtrips (parses and prints correctly between both syntax, i.e, always keep representing the same thing and not erroring), yes, it is the expected behaviour
- If you really want the fully qualified version to be used in declarative assembly syntax, MLIR's way is to have `qualified($test)` instead of just `$test` in your syntax, to enforce it; but this is not implemented yet in xDSL; but shouldn't be a big deal

For the record, I agree that the resulting syntax here is weird to read ahah - but I think it might be *functionally* correct

If you want `qualified` implemented in xDSL's declarative syntax, let's open a dedicated issue?
Also, could you then ping me again here or there? I'm not following all issues :sweat_smile:

**Comment by alexarice** [comment]
It makes sense that the attribute name can always be inferred here, it just seemed strange that this was the output to me. I have no need for the qualified flag so I'll close the issue for now
