### ISSUE TITLE
core: `module{}` parsed as an unregistered operation when `MLContext(allow_unregistered=True)`

### ISSUE THREAD

**Issue by dshaaban01** [xdslproject/xdsl#3668]
`module {}`, which is a valid spelling of builtin.module {} in MLIR, is parsed as an unregistered operation, even though it's always registered. This happens in particular when `MLContext(allow_unregistered=True)` instead of it's default, which is False.

**Comment by alexarice** [comment]
The problem is in `_get_op_by_name`. First `get_optional_op` is called on the read name, and then is afterwards called on "dialect_name.name" for every dialect seen so far. However if `allow_unregistered_op` is set, then the first call to `get_optional_op` returns an `UnregisteredOp` and the second call never happens. 

I'll submit a quick fix
