### ISSUE TITLE
Complete conversion to new irdl notation

### ISSUE THREAD

**Issue by AntonLydike** [xdslproject/xdsl#387]
I would like to collect an overview over the changes made to the irdl definition notation here.

## How to migrate:

This is a collection of easy rewrites to migrate from the old to the new notation:

```
# Attribute
= AttributeDef(StringAttr) -> : OpAttr[StringAttr]
= OptAttributeDef(StringAttr) -> OptOpAttr[StringAttr]
= VarOperandDef(RegisterType()) -> : Annotated[VarOperand, RegisterType]

# Operand
= OperandDef(StringAttr) -> : Annotated[Operand, StringAttr]
= OperandDef(AnyAttr()) -> : Annotated[Operand, Attribute] 

# Result
= ResultDef(AnyAttr()) -> Annotated[OpResult, RegisterType]
IntegerAttr -> AnyIntegerAttr
= OptResultDef(RegisterType()) -> : Annotated[OptOpResult, RegisterType]

# region def
= RegionDef() -> : Region
= SingleBlockRegionDef() -> : SingleBlockRegion
= OptRegionDef() -> : OptRegion
= VarRegionDef() -> : VarRegion
= OptSingleBlockRegionDef()-> : OptSingleBlockRegion
```

## Open Questions:

In what way are the old notations still in use, and how can we make the migration experience better?

e.g. either deleting the unused classes, or adding warnings.

I just looked through the code, and the old stuff seemed to be still in use (sort of), but isn't respected by `@irdl_op_definition` and others.

**Comment by webmiche** [comment]
AFAIU, this new way of annotating is not something entirely new, but rather something built on top of the old structure to give type checking and IDE support. Also, keep in mind that these classes are still in use, so if we actually want to print deprecation messages, we cannot print them on instantiation, otherwise our framework will be printing random deprecation messages all the time.

Personally, I am still of the opinion that we should have handled/communicated the transition better, but I don't see the value in deprecation messages (unless they are really low-hanging fruits like the ones in [dialect registration](https://github.com/xdslproject/xdsl/blob/main/xdsl/ir.py#L39)).

**Comment by AntonLydike** [comment]
I think it might be valuable to try and separate the internal from the external interfaces. Depending on the effort required, we could move the stuff we need for irdl annotations to their own module. I think this would already greatly improve usability because you could see what annotations are available (and supported) just by seeing what you can import from the `irdl.annotations` module (imaginary name).

I think part of the confusion currently is that you can import `Operand` and `OperandDef` from the same module, and one used to work, but doesn't anymore.

**Comment by math-fehr** [comment]
Just as a comment, the old notation should not work anymore, and not define anything.
However, these names are used for introspecting the definition itself. IRDL defines a `OpDef` class that represent the operation definitions.
We could think of raising an exception whenever someone is defining a field that is not an operand/result/region/attribute definition though!

**Comment by webmiche** [comment]
AFAIU, the core issue was that the old annotation can still be used (in it does not directly throw errors/warnings on definition), but the decorator completely ignores it, leading to non-intuitive failures after upgrading the xdsl version number. This is especially bad since the released version was named 0.8.1 and not 0.9.0, so only a minor-minor bump and not a minor bump. Did I summarize that properly, @AntonLydike?

**Comment by georgebisbas** [comment]
> This is especially bad since the released version was named 0.8.1 and not 0.9.0, so only a minor-minor bump and not a minor bump

We could burn 0.9 with the same release notes.

**Comment by georgebisbas** [comment]
Reminder to myself to update this

**Comment by math-fehr** [comment]
This is now completely gone, so we shouldn't have any problems.
